[package]
name = "skipper"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "CLI commander"
repository = "https://github.com/frazerk/skipper"
readme = true

[dependencies]
once_cell = "1.5.2"
